// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Log In Test 3', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Log In Test 3', async function() {
    await driver.get("https://bstackdemo.com/")
    await driver.manage().window().setRect({ width: 1440, height: 716 })
    await driver.findElement(By.id("signin")).click()
    await driver.findElement(By.css(".css-1pahdxg-control > .css-1hwfws3")).click()
    await driver.findElement(By.id("react-select-2-input")).sendKeys("demouser")
    await driver.findElement(By.id("react-select-2-input")).sendKeys(Key.ENTER)
    {
      const element = await driver.findElement(By.id("login-btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-1wa3eu0-placeholder")).click()
    await driver.findElement(By.id("react-select-3-input")).sendKeys("testingisfun")
    await driver.findElement(By.id("react-select-3-input")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("login-btn")).click()
  })
})
